#!/bin/bash
# Test 1: Sending email via AppleScript
# Use case: Claude drafts email → send via Mail.app

echo "=== Test 1: Sending Email via Mail.app ==="
echo ""
echo "This test will:"
echo "1. Create a new email message"
echo "2. Set recipients, subject, and body"
echo "3. Either send immediately OR open for review"
echo ""

# Example 1: Send immediately (DANGEROUS - use with test email only)
send_email_immediately() {
    local to_address="$1"
    local subject="$2"
    local body="$3"

    osascript <<EOF
tell application "Mail"
    set newMessage to make new outgoing message with properties {subject:"$subject", content:"$body", visible:true}
    tell newMessage
        make new to recipient at end of to recipients with properties {address:"$to_address"}
        send
    end tell
end tell
EOF
}

# Example 2: Create draft and open for review (SAFER)
create_draft_for_review() {
    local to_address="$1"
    local subject="$2"
    local body="$3"

    osascript <<EOF
tell application "Mail"
    activate
    set newMessage to make new outgoing message with properties {subject:"$subject", content:"$body", visible:true}
    tell newMessage
        make new to recipient at end of to recipients with properties {address:"$to_address"}
    end tell
end tell
EOF
}

# Example 3: Multiple recipients (to, cc, bcc)
create_draft_with_cc_bcc() {
    local to_address="$1"
    local cc_address="$2"
    local bcc_address="$3"
    local subject="$4"
    local body="$5"

    osascript <<EOF
tell application "Mail"
    activate
    set newMessage to make new outgoing message with properties {subject:"$subject", content:"$body", visible:true}
    tell newMessage
        make new to recipient at end of to recipients with properties {address:"$to_address"}
        make new cc recipient at end of cc recipients with properties {address:"$cc_address"}
        make new bcc recipient at end of bcc recipients with properties {address:"$bcc_address"}
    end tell
end tell
EOF
}

# Run test (SAFE version - creates draft only)
echo "Creating test draft for review..."
create_draft_for_review \
    "test@example.com" \
    "Test Email from Claude Code" \
    "This is a test email created via AppleScript.

It supports multiple paragraphs.

And even line breaks.

Generated by Claude Code on $(date)"

echo ""
echo "Result: Mail.app should now be open with a draft message ready for review."
echo ""
echo "Performance: Near-instant (< 1 second)"
echo "Reliability: Very high"
echo ""
echo "NOTES:"
echo "- Use create_draft_for_review for safety (human reviews before send)"
echo "- Use send_email_immediately only for automated emails to known addresses"
echo "- Mail.app must be configured with at least one account"
echo "- The 'visible:true' property opens the compose window"
echo ""
